# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [6]:
'''
Your Code

list只會轉換第一層陣列(Array)轉成列表(List),所以如果是兩維以上陣列,則第2層還是會維持為陣列

tolist會把所有維度的陣列(Array)都轉成列表(List)

'''



'\nYour Code\n\nlist只會轉換第一層陣列(Array)轉成列表(List),所以如果是兩維以上陣列,則第2層還是會維持為陣列\n\ntolist會把所有維度的陣列(Array)都轉成列表(List)\n\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [7]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np


In [29]:
'''
Your Code
'''
a = np.random.randint(10, size=6) 

print("Array(陣列內容):\n",a)
print("NDIM(陣列維度):",a.ndim)
print("Shape(陣列各維大小):",a.shape)
print("Size(陣列內容個數):",a.size)
print("Type(陣列內容型態):",a.dtype)
print("ItemSize(個別陣列內容空間大小):",a.itemsize)
print("Len(第一維的長度):",len(a) )
print("Type(資料型態):", type(a) )

Array(陣列內容):
 [6 4 5 8 8 1]
NDIM(陣列維度): 1
Shape(陣列各維大小): (6,)
Size(陣列內容個數): 6
Type(陣列內容型態): int32
ItemSize(個別陣列內容空間大小): 4
Len(第一維的長度): 6
Type(資料型態): <class 'numpy.ndarray'>


In [30]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''

print("Array(陣列內容):\n",b)
print("NDIM(陣列維度):",b.ndim)
print("Shape(陣列各維大小):",b.shape)
print("Size(陣列內容個數):",b.size)
print("Type(陣列內容型態):",b.dtype)
print("ItemSize(個別陣列內容空間大小):",b.itemsize)
print("Len(第一維的長度):",len(b) )
print("Type(資料型態):", type(b) )

Array(陣列內容):
 [[7 3 6 0]
 [6 4 8 2]
 [7 6 7 2]]
NDIM(陣列維度): 2
Shape(陣列各維大小): (3, 4)
Size(陣列內容個數): 12
Type(陣列內容型態): int32
ItemSize(個別陣列內容空間大小): 4
Len(第一維的長度): 3
Type(資料型態): <class 'numpy.ndarray'>


In [31]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''

print("Array(陣列內容):\n",c)
print("NDIM(陣列維度):",c.ndim)
print("Shape(陣列各維大小):",c.shape)
print("Size(陣列內容個數):",c.size)
print("Type(陣列內容型態):",c.dtype)
print("ItemSize(個別陣列內容空間大小):",c.itemsize)
print("Len(第一維的長度):",len(c) )
print("Type(資料型態):", type(c) )

Array(陣列內容):
 [[[4 3]
  [9 4]
  [8 3]]

 [[2 7]
  [7 3]
  [9 2]]]
NDIM(陣列維度): 3
Shape(陣列各維大小): (2, 3, 2)
Size(陣列內容個數): 12
Type(陣列內容型態): int32
ItemSize(個別陣列內容空間大小): 4
Len(第一維的長度): 2
Type(資料型態): <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [39]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

for d1 in a:
       print(d1,end=" ")


[4, 0, 9, 2, 3, 7]
[4, 0, 9, 2, 3, 7]
4 0 9 2 3 7 

In [45]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))
print()
for d1 in list(b):
    for d2 in list(d1):
       print(d2,end=" ")
    print()

[[5, 4, 7, 3], [9, 6, 0, 7], [9, 0, 8, 1]]
[array([5, 4, 7, 3]), array([9, 6, 0, 7]), array([9, 0, 8, 1])]

5 4 7 3 
9 6 0 7 
9 0 8 1 


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))
print()
for d1 in list(b):
    for d2 in list(d1):
       print(d2,end=" ")
    print()

[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [ ]:
def tolist(iterable):
    '''
    Your Code
    '''

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
