# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
'''
Your Code

zeros 是產生0
empty 是產生靠近0的質

'''

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [4]:
# 參考解答

a = np.random.rand(2, 3)

'''
Your Code
'''

b=a.copy().round()
print(a)
print()
print(b)

[[0.17472788 0.15266871 0.47759467]
 [0.33825355 0.76176235 0.04032199]]

[[0. 0. 0.]
 [0. 1. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [6]:
m = 20
n = 40

'''
Your Code
'''

'\nYour Code\n'

In [7]:
from numpy.random import default_rng
integers = default_rng().integers(m, n, size=(2,3))
print(integers)

[[23 38 23]
 [31 26 29]]
