# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [7]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np
a=np.arange(1,12)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [22]:
'''
Your Code
'''
a[2:6] = -1 * a[2:6]
a

array([ 1,  2, -3, -4, -5, -6,  7,  8,  9, 10, 11])

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [30]:
A = np.random.rand(3, 6)

'''
Your Code
'''
print(A)
print(A[A>0.5].size )

[[0.5046417  0.27905082 0.11256879 0.75474902 0.87109784 0.91165985]
 [0.21087775 0.84444759 0.41274787 0.03922694 0.06986354 0.12669016]
 [0.52919403 0.56988644 0.72130913 0.65002732 0.39654633 0.29958478]]
9
