# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
'''
Your Code
都一樣
'''

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np 


In [3]:
A = np.random.random((5, 5))

'''
Your Code
'''
print(A.clip(0, 1))

[[0.92892031 0.0909117  0.63804822 0.48535709 0.79111136]
 [0.01628253 0.04492467 0.18066243 0.45856895 0.11838578]
 [0.10420472 0.14939219 0.52744283 0.79710306 0.4728598 ]
 [0.59545409 0.94368815 0.44215311 0.59579778 0.34873832]
 [0.84708887 0.95630346 0.86774257 0.4750959  0.75610611]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [31]:
'''
Your Code
'''
#A = np.arange(10)
A=np.random.randint(0,100,10)

In [32]:
A

array([28, 60,  3,  0, 76, 91, 89, 21, 47, 67])

In [33]:
A[A.argmax()]=-1

In [34]:
A

array([28, 60,  3,  0, 76, -1, 89, 21, 47, 67])